
__all__ = ['SCREEN_WIDTH',
           'SCREEN_HEIGHT',
           'PERCEPTION_DISTANCE',
           'SEPARATION_DISTANCE',
           'ALIGNMENT_GAIN',
           'COHESION_GAIN',
           'SEPARATION_GAIN',
           'NUM_ENTITIES',
           'MAX_SPEED',
           'MIN_SPEED',
           'STEERING_GAIN',
           'COLLISION_THRESHOLD']


SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800
PERCEPTION_DISTANCE = 100
SEPARATION_DISTANCE = 80
ALIGNMENT_GAIN = 0.0005
COHESION_GAIN = 0.0006
SEPARATION_GAIN = 0.85
NUM_ENTITIES = 50
MAX_SPEED = 4
MIN_SPEED = 2
STEERING_GAIN = 0.8
COLLISION_THRESHOLD = 50
