
__all__ = ['SCREEN_WIDTH',
           'SCREEN_HEIGHT',
           'PERCEPTION_DISTANCE',
           'SEPARATION_DISTANCE',
           'ALIGNMENT_GAIN',
           'COHESION_GAIN',
           'SEPARATION_GAIN',
           'NUM_ENTITIES',
           'MAX_SPEED',
           'MIN_SPEED',
           'STEERING_GAIN']


SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800
PERCEPTION_DISTANCE = 50
SEPARATION_DISTANCE = 20
ALIGNMENT_GAIN = 0.1
COHESION_GAIN = 0.6
SEPARATION_GAIN = 0.005
NUM_ENTITIES = 50
MAX_SPEED = 4
MIN_SPEED = 2
STEERING_GAIN = 45